name: Print Hello World

on:
  push:
    branches:
      - main

jobs:
  hello-world-job:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Print Hello World
        run: echo "Hello World"
      - name: Build file
        run: npm run build
